server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: "default"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
topic:
  name: t.food.order
